/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod'

/**
 * Vytvoří nového hráče s přezdívkou a volitelným skóre. Pokud skóre není zadáno, nastaví se výchozí hodnota. Vrací pouze tělo odpovědi.
 * @summary Vytvořit nového hráče
 */
export const addPlayerBodyNicknameMin = 3;

export const addPlayerBodyNicknameMax = 50;
export const addPlayerBodyScoreMin = 0;


export const addPlayerBody = zod.object({
  "nickname": zod.string().min(addPlayerBodyNicknameMin).max(addPlayerBodyNicknameMax),
  "score": zod.number().min(addPlayerBodyScoreMin).optional()
})

/**
 * Vrací údaje o jednom hráči na základě jeho unikátního ID.
 * @summary Získat hráče podle ID
 */
export const getPlayerParams = zod.object({
  "playerId": zod.number()
})

/**
 * Odstraní hráče z databáze a vrátí data smazaného hráče.
 * @summary Smazat hráče
 */
export const deletePlayerParams = zod.object({
  "playerId": zod.number()
})

/**
 * Částečně aktualizuje údaje hráče. Můžete poslat pouze pole, která chcete změnit (např. jen přezdívku nebo jen skóre).
 * @summary Aktualizovat hráče
 */
export const updatePlayerParams = zod.object({
  "playerId": zod.number()
})

export const updatePlayerBodyNicknameMin = 3;

export const updatePlayerBodyNicknameMax = 50;
export const updatePlayerBodyScoreMin = 0;


export const updatePlayerBody = zod.object({
  "nickname": zod.string().min(updatePlayerBodyNicknameMin).max(updatePlayerBodyNicknameMax).optional(),
  "score": zod.number().min(updatePlayerBodyScoreMin).optional()
})

