/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod'

/**
 * Vytvoří nového hráče s přezdívkou. Počáteční skóre nastavuje backend na výchozí hodnotu.
 * @summary Vytvořit záznam nového hráče
 */
export const addPlayerBodyNicknameMin = 3;

export const addPlayerBodyNicknameMax = 50;


export const addPlayerBody = zod.object({
  "nickname": zod.string().min(addPlayerBodyNicknameMin).max(addPlayerBodyNicknameMax)
})

/**
 * Vrací údaje o jednom hráči na základě jeho unikátního ID.
 * @summary Získat hráče podle ID
 */
export const getPlayerParams = zod.object({
  "playerId": zod.number()
})

/**
 * Částečně aktualizuje údaje hráče. Můžete poslat pouze pole, která chcete změnit (např. jen přezdívku nebo jen skóre).
 * @summary Aktualizovat hráče
 */
export const updatePlayerParams = zod.object({
  "playerId": zod.number()
})

export const updatePlayerBodyNicknameMin = 3;

export const updatePlayerBodyNicknameMax = 50;
export const updatePlayerBodyScoreMin = 0;


export const updatePlayerBody = zod.object({
  "nickname": zod.string().min(updatePlayerBodyNicknameMin).max(updatePlayerBodyNicknameMax).optional(),
  "score": zod.number().min(updatePlayerBodyScoreMin).optional()
})

/**
 * Vrací score a potential_score pro session_id z requestu. Pokud session_id chybí, vrátí se výchozí hodnoty bez výpočtu session statistik.
 * @summary Získat souhrn skóre hráče
 */
export const getPlayerSummaryParams = zod.object({
  "playerId": zod.number()
})

export const getPlayerSummaryQueryParams = zod.object({
  "session_id": zod.string().optional()
})

