## Frontend helping commands
dev:
	echo "Running frontend development server..."
	npm run dev

lint:
	echo "Running frontend linting..."
	npm run lint

build:
	echo "Building frontend..."
	npm run build

preview:
	echo "Running frontend preview server..."
	npm run preview

api-generate:
	echo "Generating api..."
	npm run api:generate