/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod'

/**
 * Vrátí seznam náhodných phishingových otázek filtrovaných podle obtížnosti. Limit je omezen na maximálně 100 otázek. Pokud pro danou obtížnost neexistují otázky, vrátí se prázdný seznam.
 * @summary Získat náhodné otázky podle obtížnosti
 */
export const getRandomQuestionsByDifficultyQueryParams = zod.object({
  "difficulty": zod.enum(['EASY', 'MEDIUM', 'HARD']),
  "limit": zod.number()
})

export const getRandomQuestionsByDifficultyResponse = zod.string()

