/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod'

/**
 * Vrátí seznam náhodných phishingových otázek filtrovaných podle obtížnosti. Limit je omezen na maximálně 100 otázek. Pokud pro danou obtížnost neexistují otázky, vrátí se prázdný seznam.
 * @summary Získat náhodné otázky podle obtížnosti
 */
export const getRandomQuestionsByDifficultyQueryParams = zod.object({
  "difficulty": zod.enum(['EASY', 'MEDIUM', 'HARD']),
  "limit": zod.number()
})

export const getRandomQuestionsByDifficultyResponseItem = zod.object({
  "id": zod.number().optional(),
  "platform": zod.string().optional(),
  "metadata": zod.object({
  "sender": zod.string().optional(),
  "subject": zod.string().optional()
}).optional(),
  "content": zod.string().optional(),
  "explanation": zod.string().optional()
})
export const getRandomQuestionsByDifficultyResponse = zod.array(getRandomQuestionsByDifficultyResponseItem)

