-- Flyway migrace V1: Vytvoření tabulky hráčů
-- Tato migrace vytváří počáteční schéma pro tabulku hráčů

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    score INT NOT NULL DEFAULT 100
);

-- NOTE: nickname already has a UNIQUE constraint which creates a backing index