-- Tabulka platformních typů (email, SMS, atd.)
CREATE TABLE platform_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- Tabulka fišinkových kategorií (FAKE_URL, URGENT, atd.)
CREATE TABLE phishing_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(250) NOT NULL,
    security_hints JSONB DEFAULT '[]'::jsonb
);

-- Tabulka otázek
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_type_id BIGINT NOT NULL REFERENCES platform_types(id),
    is_phishing BOOLEAN NOT NULL,
    difficulty INTEGER NOT NULL,
    penalty INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    explanation VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Spojovací tabulka mezi otázkami a kategoriemi
CREATE TABLE question_to_categories (
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES phishing_categories(id) ON DELETE CASCADE,
    PRIMARY KEY (question_id, category_id)
);

-- Indexy pro zrychlení dotazů
CREATE INDEX idx_questions_platform_type_id ON questions(platform_type_id);
CREATE INDEX idx_question_to_categories_question_id ON question_to_categories(question_id);
CREATE INDEX idx_question_to_categories_category_id ON question_to_categories(category_id);
CREATE INDEX idx_phishing_categories_tag ON phishing_categories(tag);
