INSERT INTO players (id, nickname, score) VALUES (1, 'singhaTheRulerOfAllWorlds001', 100);
INSERT INTO players (id, nickname, score) VALUES (2, 'CyberEli', 99);
INSERT INTO players (id, nickname, score) VALUES (3, 'NikByte', 43);
INSERT INTO players (id, nickname, score) VALUES (4, 'ReneRoot', 77);
INSERT INTO players (id, nickname, score) VALUES (5, 'Čičina♥', 89);
INSERT INTO players (id, nickname, score) VALUES (6, 'Král 🐸 žabák', 0);
INSERT INTO players (id, nickname, score) VALUES (7, 'ZeroTrust', 13);
INSERT INTO players (id, nickname, score) VALUES (8, '   náhodný   mezery   ', 1);
INSERT INTO players (id, nickname, score) VALUES (9, 'Cloud_buster', 53);
INSERT INTO players (id, nickname, score) VALUES (10, 'd1v0c4k_!!!', 13);
INSERT INTO players (id, nickname, score) VALUES (11, 'xX_no0bSl4yer_Xx!!!🔥', 64);
INSERT INTO players (id, nickname, score) VALUES (12, '🧅🥲 cebulka_master', 5);
INSERT INTO players (id, nickname, score) VALUES (13, '   omylem   mezery    všude   ', 22);
INSERT INTO players (id, nickname, score) VALUES (14, 'D3F4ULT___USR???', 71);
INSERT INTO players (id, nickname, score) VALUES (15, '😈💀 FINAL_BOSS_420 💀😈', 95);
INSERT INTO players (id, nickname, score) VALUES (16, 'hej!proc_to_nefunguje??', 11);
INSERT INTO players (id, nickname, score) VALUES (17, 'kOcOuR_žÍžAlA_88', 44);
INSERT INTO players (id, nickname, score) VALUES (18, 'XDxdXDxdXd   ', 8);
INSERT INTO players (id, nickname, score) VALUES (19, 'pr@šiv#ák!_69', 1);
INSERT INTO players (id, nickname, score) VALUES (20, '🌪️..tornado_homyx..🌪️', 76);
INSERT INTO players (id, nickname, score) VALUES (21, '🤖_MegaUltraBotDestroyer9000_⚡', 73);
INSERT INTO players (id, nickname, score) VALUES (22, 'shadow_king_of_darkness_🔥💀', 42);
INSERT INTO players (id, nickname, score) VALUES (23, '☠️xXx_FATALITY_MASTER_3000_xXx', 12);
INSERT INTO players (id, nickname, score) VALUES (24, 'superLongNickName_becauseWHY?!', 9);
INSERT INTO players (id, nickname, score) VALUES (25, '🍕HungryPlayerWhoEatsAllTime🍕', 55);
INSERT INTO players (id, nickname, score) VALUES (26, 'ERROR_404_username_not_found😵', 87);
INSERT INTO players (id, nickname, score) VALUES (27, '⚔️KnightOfTheLaggingRealm_123⚔️', 14);
INSERT INTO players (id, nickname, score) VALUES (28, '🐸spong3b0b_m3m3_L0RD_ultimate🐸', 28);
INSERT INTO players (id, nickname, score) VALUES (29, '🔥🔥unlimited_power_overflow_99', 63);
INSERT INTO players (id, nickname, score) VALUES (30, 'Too_Many_Characters_But_Fine😅', 3);
INSERT INTO players (id, nickname, score) VALUES (31, 'Žluťoučký_Kůň✨', 12);
INSERT INTO players (id, nickname, score) VALUES (32, 'lol_xd_🤡', 4);
INSERT INTO players (id, nickname, score) VALUES (33, 'R@nd0mUser?!!', 39);
INSERT INTO players (id, nickname, score) VALUES (34, 'UTF8_Šílenec💥', 27);
INSERT INTO players (id, nickname, score) VALUES (35, '404nicknameNotHere', 5);
INSERT INTO players (id, nickname, score) VALUES (36, ';;;DROP_TABLE_USER;;;', 1);
INSERT INTO players (id, nickname, score) VALUES (37, 'Čundrák_v_lese🌲', 44);
INSERT INTO players (id, nickname, score) VALUES (38, 'za_malo😂_pane', 8);
INSERT INTO players (id, nickname, score) VALUES (39, 'xXx_xoxo_kitty_xXx', 22);
INSERT INTO players (id, nickname, score) VALUES (40, '🥒nakl@dačka🥒', 9);
INSERT INTO players (id, nickname, score) VALUES (41, 'mega⚡lagger9000', 63);
INSERT INTO players (id, nickname, score) VALUES (42, 'žádnej_nápad😂', 14);
INSERT INTO players (id, nickname, score) VALUES (43, '🧅OnionSlayer🧅', 19);
INSERT INTO players (id, nickname, score) VALUES (44, 'pepeLaugh🤣', 7);
INSERT INTO players (id, nickname, score) VALUES (45, 'mrk3v_kungfu🥋', 33);
INSERT INTO players (id, nickname, score) VALUES (46, 'Z0X', 17);
INSERT INTO players (id, nickname, score) VALUES (47, '🔥🐸👑💀', 4);
INSERT INTO players (id, nickname, score) VALUES (48, 'Lord_Cyber_Tatínek3000', 55);
INSERT INTO players (id, nickname, score) VALUES (49, 'MalySniper007Pro', 21);
INSERT INTO players (id, nickname, score) VALUES (50, 'N1ghtM4re_Ex3cut0r', 63);
INSERT INTO players (id, nickname, score) VALUES (51, 'gͧͣ͌ͫͬl̶̶ͬi̷̸ͯt̷ͤc̶͒͗̎h͐͒͝', 8);
INSERT INTO players (id, nickname, score) VALUES (52, 'SakraTyJsiTrdloXD', 31);
INSERT INTO players (id, nickname, score) VALUES (53, '"DROP TABLE users;--"', 12);
INSERT INTO players (id, nickname, score) VALUES (54, 'P0m3l0_Quantum_Ninja', 44);
INSERT INTO players (id, nickname, score) VALUES (55, '🔥', 2);
INSERT INTO players (id, nickname, score) VALUES (56, '💀', 9);
INSERT INTO players (id, nickname, score) VALUES (57, '🐸', 14);
INSERT INTO players (id, nickname, score) VALUES (58, '?!', 3);
INSERT INTO players (id, nickname, score) VALUES (59, '⚡', 1);
INSERT INTO players (id, nickname, score) VALUES (60, 'XD', 20);
INSERT INTO players (id, nickname, score) VALUES (61, '🧅', 7);
INSERT INTO players (id, nickname, score) VALUES (62, '🤖', 11);
INSERT INTO players (id, nickname, score) VALUES (63, '🔥🐸', 18);
INSERT INTO players (id, nickname, score) VALUES (64, '_', 5);
INSERT INTO players (id, nickname, score) VALUES (65, 'Q', 12);
INSERT INTO players (id, nickname, score) VALUES (66, '🌀', 4);
INSERT INTO players (id, nickname, score) VALUES (67, '💣BOOM', 33);
INSERT INTO players (id, nickname, score) VALUES (68, 'F1reFly✨', 47);
INSERT INTO players (id, nickname, score) VALUES (69, 'N@h0dny_Zn@k', 28);
INSERT INTO players (id, nickname, score) VALUES (70, 'm͑ͩ̒͗͒̾̾a͐ͤ̽ͪͥͨs̓̄̋̌͂̇oͧ͊̏̍', 6);
INSERT INTO players (id, nickname, score) VALUES (71, '‏‏‎ ‎InvisibleBoy‎‏‏‎ ‎', 5);
INSERT INTO players (id, nickname, score) VALUES (72, 'zero width spaces', 8);
INSERT INTO players (id, nickname, score) VALUES (73, 'longggggggggggggggggggggggggg🤯', 11);
INSERT INTO players (id, nickname, score) VALUES (74, 'Aͯ̄͗͆ͭͣͨ͛ͤ̋ͤ̅̎', 9);
INSERT INTO players (id, nickname, score) VALUES (75, '🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥', 14);
INSERT INTO players (id, nickname, score) VALUES (76, 'line\nbreak', 4);
INSERT INTO players (id, nickname, score) VALUES (77, '　　　lots_of_spaces　　　', 2);
INSERT INTO players (id, nickname, score) VALUES (78, 'RTL_‏‏‎test‏‏‎_🔥', 7);
INSERT INTO players (id, nickname, score) VALUES (79, '𝕊𝕦𝕡𝕖𝕣𝔽𝕠𝕟𝕥', 13);
INSERT INTO players (id, nickname, score) VALUES (80, 'xss_test_escaped', 1);
INSERT INTO players (id, nickname, score) VALUES (81, '''quotes_everywhere''', 12);
INSERT INTO players (id, nickname, score) VALUES (82, '/////////', 6);
INSERT INTO players (id, nickname, score) VALUES (83, '🐛bug🐛bug🐛bug🐛', 15);
INSERT INTO players (id, nickname, score) VALUES (84, '🤡ClownMode🤡', 23);
INSERT INTO players (id, nickname, score) VALUES (85, '😇🙃🙂😉😏', 17);
INSERT INTO players (id, nickname, score) VALUES (86, '❗❗❗ERROR❗❗❗', 9);
INSERT INTO players (id, nickname, score) VALUES (87, '„‚…†‡‰Š‹ŒžŸ', 18);
INSERT INTO players (id, nickname, score) VALUES (88, 'emoji‍‍‍cluster‍‍‍test', 21);
INSERT INTO players (id, nickname, score) VALUES (89, 'dvojity̌̌test', 10);
INSERT INTO players (id, nickname, score) VALUES (90, '¯\_(ツ)_/¯', 33);

-- Reset auto-increment sequence for next inserts
ALTER TABLE players ALTER COLUMN id RESTART WITH 91;
