CREATE TABLE phishing_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(250) NOT NULL,
    security_hints JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_type_id INTEGER NOT NULL CHECK (platform_type_id IN (1, 2)),
    is_phishing BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL REFERENCES phishing_categories(id) ON DELETE CASCADE,
    difficulty INTEGER NOT NULL,
    penalty INTEGER NOT NULL,
    content VARCHAR(3000) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    explanation VARCHAR(3000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--- INDEXES FOR PERFORMANCE AND INTEGRITY
CREATE UNIQUE INDEX idx_questions_content_hash_per_platform
    ON questions (platform_type_id, md5(content));
CREATE INDEX idx_questions_platform_type_id
    ON questions(platform_type_id);
CREATE INDEX idx_phishing_categories_tag
    ON phishing_categories(tag);