spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hack_me_if_you_can_dev
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
