/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod'

/**
 * Vrátí detail jedné phishing kategorie podle tagu. Vyhledávání tagu je case-insensitive.
 * @summary Získat detail phishing kategorie podle tagu
 */
export const getPhishingCategoryByTagParams = zod.object({
  "tag": zod.string()
})

