-- Init Players table
INSERT INTO players (nickname)
VALUES
    ('singhaTheRulerOfAllWorlds001'),
    ('CyberEli'),
    ('NikByte'),
    ('ReneRoot'),
    ('Čičina♥'),
    ('Král 🐸 žabák'),
    ('ZeroTrust'),
    ('   náhodný   mezery   '),
    ('Cloud_buster'),
    ('d1v0c4k_!!!'),
    ('xX_no0bSl4yer_Xx!!!🔥'),
    ('🧅🥲 cebulka_master'),
    ('   omylem   mezery    všude   '),
    ('D3F4ULT___USR???'),
    ('😈💀 FINAL_BOSS_420 💀😈'),
    ('hej!proc_to_nefunguje??'),
    ('kOcOuR_žÍžAlA_88'),
    ('XDxdXDxdXd   '),
    ('pr@šiv#ák!_69'),
    ('🌪️..tornado_homyx..🌪️'),
    ('🤖_MegaUltraBotDestroyer9000_⚡'),
    ('shadow_king_of_darkness_🔥💀'),
    ('☠️xXx_FATALITY_MASTER_3000_xXx'),
    ('superLongNickName_becauseWHY?!'),
    ('🍕HungryPlayerWhoEatsAllTime🍕'),
    ('ERROR_404_username_not_found😵'),
    ('⚔️KnightOfTheLaggingRealm_123⚔️'),
    ('🐸spong3b0b_m3m3_L0RD_ultimate🐸'),
    ('🔥🔥unlimited_power_overflow_99'),
    ('Too_Many_Characters_But_Fine😅'),
    ('Žluťoučký_Kůň✨'),
    ('lol_xd_🤡'),
    ('R@nd0mUser?!!'),
    ('UTF8_Šílenec💥'),
    ('404nicknameNotHere'),
    (';;;DROP_TABLE_USER;;;'),
    ('Čundrák_v_lese🌲'),
    ('za_malo😂_pane'),
    ('xXx_xoxo_kitty_xXx'),
    ('🥒nakl@dačka🥒'),
    ('mega⚡lagger9000'),
    ('žádnej_nápad😂'),
    ('🧅OnionSlayer🧅'),
    ('pepeLaugh🤣'),
    ('mrk3v_kungfu🥋'),
    ('Z0X'),
    ('🔥🐸👑💀'),
    ('Lord_Cyber_Tatínek3000'),
    ('MalySniper007Pro'),
    ('N1ghtM4re_Ex3cut0r'),
    ('gͧͣ͌ͫͬl̶̶ͬi̷̸ͯt̷ͤc̶͒͗̎h͐͒͝'),
    ('SakraTyJsiTrdloXD'),
    ('"DROP TABLE users;--"'),
    ('P0m3l0_Quantum_Ninja'),
    ('🔥'),
    ('💀'),
    ('🐸'),
    ('?!'),
    ('⚡'),
    ('XD'),
    ('🧅'),
    ('🤖'),
    ('🔥🐸'),
    ('_'),
    ('Q'),
    ('🌀'),
    ('💣BOOM'),
    ('F1reFly✨'),
    ('N@h0dny_Zn@k'),
    ('m͑ͩ̒͗͒̾̾a͐ͤ̽ͪͥͨs̓̄̋̌͂̇oͧ͊̏̍'),
    ('‏‏‎ ‎InvisibleBoy‎‏‏‎ ‎'),
    ('zero width spaces'),
    ('longggggggggggggggggggggggggg🤯'),
    ('Aͯ̄͗͆ͭͣͨ͛ͤ̋ͤ̅̎'),
    ('🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥'),
    ('line\nbreak'),
    ('　　　lots_of_spaces　　　'),
    ('RTL_‏‏‎test‏‏‎_🔥'),
    ('𝕊𝕦𝕡𝕖𝕣𝔽𝕠𝕟𝕥'),
    ('xss_test_escaped'),
    ('''quotes_everywhere'''),
    ('/////////'),
    ('🐛bug🐛bug🐛bug🐛'),
    ('🤡ClownMode🤡'),
    ('😇🙃🙂😉😏'),
    ('❗❗❗ERROR❗❗❗'),
    ('„‚…†‡‰Š‹ŒžŸ'),
    ('emoji‍‍‍cluster‍‍‍test'),
    ('dvojity̌̌test'),
    ('¯\_(ツ)_/¯')
ON CONFLICT (nickname) DO NOTHING;

-- Init Phishing Categories table
INSERT INTO phishing_categories (tag, name, description, reward_points, security_hints)
VALUES ('LEGIT',
        'Legitimní zpráva / Bezpečný obsah',
        'Zprávy, které jsou autentické, pocházejí od důvěryhodných odesílatelů a neobsahují žádné škodlivé prvky.',
        100,
        '[
          "Doména odesílatele (část za zavináčem) přesně odpovídá oficiální webové adrese služby (např. @alza.cz, @paypal.com, @csob.cz).",
          "Zpráva je očekávaná a přímo související s vaší nedávnou aktivitou (např. potvrzení objednávky, kterou jste právě odeslali, nebo kód pro obnovu hesla, o který jste sami požádali).",
          "Odkazy po najetí myší (hover) směřují přímo na oficiální doménu služby bez podezřelých poddomén nebo zkracovačů (jako bit.ly či tinyurl) v citlivé komunikaci.",
          "Oficiální instituce vás nikdy nežádají o zaslání citlivých údajů (heslo, PIN, CVV kód) přímo v textu zprávy ani přes odkaz v ní.",
          "Zpráva postrádá prvky manipulace, jako je uměle vyvolaný strach, časový nátlak nebo sliby nereálných výher.",
          "Komunikace je profesionální, bez gramatických chyb a s logickým formátováním, které odpovídá vizuální identitě dané značky."
        ]'::jsonb),
       ('FAKE_URL',
        'Falešné URL / Neodpovídající doména',
        'Útoky využívající vizuální podobnost adres nebo podvržené odkazy, které vypadají jako legitimní, ale směřují jinam.',
        600,
        '[
          "Vždy najeď myší nad odkaz (hovering) a sleduj levý dolní roh prohlížeče. Tam uvidíš skutečný cíl, který se může lišit od textu, na který klikáš.",
          "Čti doménu zprava doleva. Hlavní doména je ta těsně před koncovkou (.cz, .com). Například u `microsoft.security-update.com` je skutečným majitelem `security-update.com`, nikoliv Microsoft.",
          "Hledej drobné záměny znaků (tzv. typosquatting). Útočníci často mění `m` za `rn`, `l` za `1`, nebo přidávají nenápadnou pomlčku (např. `ceska-posta.cz` místo `ceskaposta.cz`).",
          "Nenech se zmást symbolem zámku (HTTPS). Zelený zámek znamená pouze to, že spojení je šifrované, nikoliv že web patří důvěryhodné firmě.",
          "Pozor na zkrácené odkazy (např. bit.ly, tinyurl). Oficiální instituce jako banky nebo státní úřady je v e-mailech k přihlašování téměř nikdy nepoužívají.",
          "Pokud odkaz vede na IP adresu (např. http://192.168.1.1/login), je to téměř jistě podvod."
        ]'::jsonb),
       ('URGENT',
        'Urgentní žádost / Sociální inženýrství',
        'Manipulativní techniky, které zneužívají autoritu, strach z postihu nebo časový nátlak k vynucení neuvážené akce.',
        500,
        '[
          "Zpozorni u každé zprávy, která vyžaduje „okamžitou akci“, jinak hrozí „smazání účtu“, „pokuta“ nebo „právní postih“. Časový nátlak je hlavním nástrojem útočníků.",
          "Ověřuj identitu odesílatele jiným kanálem. Pokud ti píše šéf nebo kolega neobvyklou žádost (např. o platbu nebo zaslání údajů), raději mu zavolej nebo napiš na interní chat.",
          "Sleduj tón zprávy. Působí e-mail nezvykle familiárně, nebo naopak příliš agresivně? Útočníci často neznají přesný styl komunikace ve vaší firmě.",
          "Buď podezřívavý k požadavkům na nestandardní platební metody (např. nákup dárkových karet, kryptoměny nebo převod na soukromý účet bankéře).",
          "Všímej si drobností v oslovení. Legitimní firmy tě většinou oslovují jménem, zatímco phishing často používá obecné „Vážený zákazníku“ nebo „Drahý uživateli“.",
          "Pamatuj, že banka ani státní úřad po tobě nikdy nebudou chtít heslo nebo PIN přes e-mail, ani tě nebudou nutit k převodu peněz pod záminkou „napadeného účtu“."
        ]'::jsonb),
       ('FAKE_DOC',
        'Falešná faktura / Falešný dokument',
        'Podvodné e-maily obsahující přílohy nebo odkazy na dokumenty, které mají za cíl infikovat zařízení virem nebo vylákat platební údaje.',
        700,
        '[
          "Nečekané faktury neotevírej. Pokud ti přijde faktura od služby, kterou nevyužíváš (např. jiný mobilní operátor), je to jasný varovný signál.",
          "Kontroluj přípony souborů. Útočníci často maskují spustitelné soubory jako dokumenty (např. `faktura.pdf.exe` nebo `uctenka.zip`). Pokud přípona neodpovídá typu dokumentu, soubor nespouštěj.",
          "Nikdy nepovoluj makra v dokumentech (Word, Excel). Pokud tě dokument po otevření vyzve k „povolení obsahu“ nebo „aktivaci maker“, okamžitě jej zavři – je to cesta k instalaci viru.",
          "Ověř si odesílatele. Faktura od velké firmy (např. ČEZ, Alza, O2) nikdy nepřijde z podezřelé nebo bezplatné adresy (např. `faktura123@seznam.cz` nebo `admin@eu-podpora.net`).",
          "Srovnej detaily. Pokud se částka nebo variabilní symbol neshoduje s tvými předchozími platbami, které najdeš v oficiálním internetovém bankovnictví nebo klientské zóně, je to podvod.",
          "Místo přílohy použij oficiální portál. Bezpečnější než klikat na odkaz v e-mailu je přihlásit se přímo do klientského portálu dané firmy a fakturu si stáhnout tam."
        ]'::jsonb),
       ('CRED_THEFT',
        'Sběr přihlašovacích údajů (falešný login)',
        'Podvodné stránky, které vypadají jako věrná kopie přihlašovacích obrazovek známých služeb (Google, Microsoft, banky), s cílem ukrást vaše heslo a 2FA kódy.',
        900,
        '[
          "Adresní řádek je jediný nezfalšovatelný důkaz. Vždy zkontroluj, zda doména přesně odpovídá (např. `accounts.google.com` vs. `accounts-google.net`).",
          "Pamatuj, že vizuální stránka se kopíruje nejsnadněji. To, že vidíš logo své banky a známé barvy, neznamená, že jsi na jejím webu.",
          "Zpozorni, pokud tě e-mail nutí k přihlášení pod záminkou „neobvyklé aktivity“ nebo „nutné aktualizace údajů“. Legitimní služby tě raději vyzvou, abys šel do jejich aplikace.",
          "Najeď myší na tlačítko „Přihlásit se“ (hover) ještě v e-mailu. Pokud adresa dole v rohu prohlížeče vypadá podezřele nebo je velmi dlouhá a nepřehledná, neklikej.",
          "Používej správce hesel. Pokud máš uložené heslo pro daný web, správce ho na falešné doméně automaticky nevyplní – to je okamžité varování, že jsi na podvodu.",
          "Aktivuj si dvoufázové ověření (2FA). I když útočník získá tvé heslo přes falešný login, bez kódu z mobilu nebo fyzického klíče se k účtu nedostane."
        ]'::jsonb),
       ('SPEAR_PHISH',
        'Personalizovaný útok (sociální inženýrství na míru)',
        'Vysoce cílený útok (Spear Phishing), který využívá konkrétní informace o vás (jméno, pozice, kolegové, nedávné aktivity), aby působil maximálně důvěryhodně.',
        1000,
        '[
          "To, že odesílatel zná vaše jméno nebo pracovní pozici, neznamená, že je zpráva bezpečná. Tyto údaje lze snadno získat z LinkedInu nebo firemních webů.",
          "Prověřte komunikační kanál. Pokud vám ředitel firmy (CEO), se kterým běžně nemluvíte, najednou píše přímý e-mail s urgentní žádostí, je to extrémně podezřelé.",
          "Sledujte detaily, které „nesedí“. Používá kolega v e-mailu tykání, i když si běžně vykáte? Je tón zprávy nezvykle formální nebo naopak příliš urgentní?",
          "Buďte opatrní na zmínky o konkrétních událostech. Útočníci často zmiňují konference nebo projekty, kterých jste se účastnili, aby získali vaši důvěru.",
          "Vždy si neobvyklou žádost potvrďte jinou cestou (osobně, telefonem, interním chatem). Nepoužívejte kontaktní údaje uvedené přímo v podezřelém e-mailu.",
          "Pamatujte, že útočník může napodobit i e-mailovou adresu vašeho kolegy (tzv. spoofing). Pokud se vám obsah zprávy nezdá, nevěřte ani jménu odesílatele."
        ]'::jsonb),
       ('LOTTERY',
        'Soutěžní / loterijní phishing',
        'Zprávy slibující lákavé výhry (iPhony, peněžní obnosy, dárkové poukazy), které se snaží vylákat platební údaje nebo osobní data pod záminkou "doručení výhry".',
        250,
        '[
          "Základní pravidlo: Pokud jste se žádné soutěže aktivně neúčastnili, nemůžete v ní vyhrát. Žádná firma nerozdává hodnotné ceny náhodným lidem na internetu.",
          "Pozor na poplatky předem. Legitimní soutěže nikdy nevyžadují zaplacení „manipulačního poplatku“, „pojištění“ nebo „cla“ pro uvolnění výhry.",
          "Kontrolujte doménu odesílatele. Vyhráli jste u Alzy, ale e-mail přišel z adresy `info@vyhra-pro-vas.xyz`? Je to podvod.",
          "Nikdy nezadávejte údaje o platební kartě pro „ověření věku“ nebo „zaplacení poštovného“ u výhry, která má být zdarma. Právě o tyto údaje útočníkům jde.",
          "Sledujte časový nátlak. Výzvy typu „Máte jen 2 minuty na vyzvednutí své ceny“ mají zabránit vašemu kritickému myšlení.",
          "Ověřte si soutěž na oficiálních stránkách nebo sociálních sítích dané firmy. Velké kampaně jsou tam vždy dohledatelné."
        ]'::jsonb)
ON CONFLICT (tag) DO NOTHING;
